from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)

lines = [
    "Company: TechCare Support",
    "Product: SmartHome App",
    "",
    "Q: How do I reset my password?",
    "A: Go to Settings > Account > Reset Password. Enter your email and click Send OTP.",
    "",
    "",
    "Q: How do I change my password?",
    "A: Go to Settings > Security > Change Password. Enter old password and set a new one.",
    "",
    "Q: How do I enable two factor authentication?",
    "A: Go to Settings > Security > Enable 2FA. Scan the QR code with authenticator app.",
    "",
    "Q: How do I add a new device?",
    "A: Go to Home > Add Device > Select device type > Follow setup instructions.",
    "",
    "Q: How do I remove a device?",
    "A: Go to Home > Select Device > Settings > Remove Device.",
    "",
    "Q: How do I set up automation?",
    "A: Go to Automation > Create Rule > Set trigger and action > Save.",
    "",
    "Q: How do I set a schedule for my device?",
    "A: Go to Device > Schedule > Add Schedule > Set time and days.",
    "",
    "Q: How do I share device access with family?",
    "A: Go to Settings > Family Sharing > Invite Member > Enter their email.",
    "",
    "Q: What devices are compatible with SmartHome app?",
    "A: SmartHome supports WiFi, Zigbee and Bluetooth devices from major brands.",
    "",
    "Q: How do I reset a device to factory settings?",
    "A: Press and hold the reset button on the device for 10 seconds until light blinks.",
    "",
    "Q: Why is my device showing offline?",
    "A: Check WiFi connection, restart the device and ensure it is within router range.",
    "",
    "Q: How do I update device firmware?",
    "A: Go to Device > Settings > Firmware Update > Click Update if available.",
    "",
    "Q: How do I contact live chat support?",
    "A: Go to Help > Live Chat. Available Monday to Friday 9am to 6pm IST.",
    "",
    "Q: How long does refund take?",
    "A: Refunds are processed within 5 to 7 business days to your original payment method.",
    "",
    "Q: How do I cancel my subscription?",
    "A: Go to Settings > Subscription > Cancel Plan. Access continues till end of billing period.",
    "",
    "Q: What are the subscription plans available?",
    "A: We offer Basic free plan, Pro at 299 per month and Family at 499 per month.",
    "",
    "Q: How do I upgrade my plan?",
    "A: Go to Settings > Subscription > Upgrade Plan > Choose plan > Make payment.",
    "",
    "Q: Is there a free trial available?",
    "A: Yes, Pro plan comes with 14 day free trial. No credit card required.",
    "",
    "Q: How do I download my invoice?",
    "A: Go to Settings > Billing > Invoices > Select month > Download PDF.",
    "",
    "Q: What payment methods are accepted?",
    "A: We accept UPI, credit card, debit card, net banking and wallets like Paytm.",
    "",
    "Q: How do I connect my device?",
    "A: Open the app, go to Add Device, scan the QR code on your device.",
    "",
    "Q: How do I contact support?",
    "A: Email us at support@techcare.com or call 1800-123-456.",
    "",
    "Q: What is the refund policy?",
    "A: Refunds are accepted within 7 days of purchase with valid receipt.",
    "",
    "Q: App is crashing. What to do?",
    "A: Clear app cache from phone settings and reinstall the app.",

]

for line in lines:
    pdf.cell(200, 10, txt=line, ln=True)

pdf.output("data/knowledge_base.pdf")
print("PDF created successfully!")